### ISSUE TITLE
Not all required components are registered in the ServiceCollection

### ISSUE THREAD

**Issue by teknofobia** [dark-loop/functions-authorize#43] opened 2024-03-20 18:19 UTC
.Net 8.0 (new project, not upgraded)
Functions Version 4 (Isolated)

Using the example you have in `DarkLoop.Azure.Functions.Authorization.Isolated` I get the following errors:

> System.AggregateException : Some services are not able to be constructed (Error while validating the service descriptor '
ServiceType: DarkLoop.Azure.Functions.Authorization.FunctionsAuthorizationMiddleware 
Lifetime: Singleton 
ImplementationType: DarkLoop.Azure.Functions.Authorization.FunctionsAuthorizationMiddleware': Unable to resolve service for type 'DarkLoop.Azure.Functions.Authorization.IFunctionsAuthorizationProvider' while attempting to activate 'DarkLoop.Azure.Functions.Authorization.FunctionsAuthorizationMiddleware'.)

I had to fix it with a workaround by changing my startup to look like this:

```
.ConfigureFunctionsWebApplication(builder =>
{
    new FunctionsAuthorizationExtensionStartup()
        .Configure(builder);

    // Explicitly adding the extension middleware because
    // registering middleware when extension is loaded does not
    // place the middleware in the pipeline where required request
    // information is available.
    builder.UseFunctionsAuthorization();
})
```

The problem is that out of the box, the DI calls are missing for registering the internal concrete `FunctionsAuthorizationProvider` to the interface `IFunctionsAuthorizationProvider`.  The only place you have this registration is in the startup, which is not needed or used in the .net 8 functions where it uses top-level statements instead of a startup.

You also have a typo in the readme for isolated where `AddFunctionsAuthenticationation` should be `AddFunctionsAuthentication`

Thanks!

**Comment by artmasa** [comment] 2024-03-20 18:32
@teknofobia Thanks for the great feedback. I will work on these items.

**Comment by artmasa** [comment] 2024-03-20 19:14
@teknofobia I tried creating a new .NET 8 functions app and it works, which looks the same as the Isolated sample included in the repo (No startup for the app) as extensions are discovered by the framework by using the startup classes for extensions (`WorkerExtensionStartup`), not the app. The sample only uses top level statements in `Program.cs`.

Does your `Program.cs` differs from the one in `SampleIsolatedFunctions.V4`?

**Comment by teknofobia** [comment] 2024-03-21 15:32
Thanks for looking into it.

Here is my program.cs

```
var host = ApplicationConfiguration.InitializeHostBuilder()
    .Build();

host.Run();
```

And this is the method it calls for the configuration

   ```
 public static IHostBuilder InitializeHostBuilder()
    {
        return new HostBuilder()
            .ConfigureFunctionsWebApplication(builder =>
            {
                new FunctionsAuthorizationExtensionStartup()
                    .Configure(builder);
                // Explicitly adding the extension middleware because
                // registering middleware when extension is loaded does not
                // place the middleware in the pipeline where required request
                // information is available.
                builder.UseFunctionsAuthorization();
            })
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureAppConfiguration((context, builder) =>
            {
                builder.SetBasePath(context.HostingEnvironment.ContentRootPath)
                    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                    .AddEnvironmentVariables();
                
                builder.ConfigureApplication(context.HostingEnvironment);
            })
            .ConfigureServices((ctx, services) =>
            {
                services.AddApplicationInsightsTelemetryWorkerService();
                services.ConfigureFunctionsApplicationInsights();

                services.RegisterFunctions(ctx.Configuration, ctx.HostingEnvironment)
                    .RegisterInfrastructure(ctx.Configuration)
                    .RegisterApplication();
            });
    }
```

If I remove the `new FunctionsAuthorizationExtensionStartup().Configure(builder);` I get the error from my original post because it can't find the registration.  It seems to be completely ignoring your startup class unless I make the call explicitly.

The only thing different from a brand new .net 8 v4 function app that might be interfering is I am using `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` for ASP.NET Core integration.

**Comment by artmasa** [comment] 2024-03-22 11:18
@teknofobia, thanks for sharing this.
- > The only thing different from a brand new .net 8 v4 function app that might be interfering is I am using `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` for ASP.NET Core integration.

  This is actually a requirement for this framework to work. You see in my example, I'm calling `ConfigureFunctionsWebApplication`.

- When you setup a new Functions project, the call to `ConfigureFunctionsWorkerDefaults` does not exist and you shouldn't call it as it adds the default worker middleware after having added the asp.net middleware. Actually, `ConfigureFunctionsWebApplication` calls `ConfigureFunctionsWorkerDefaults` with specific instructions to take the HTTP calls all the way to the ASP.NET core handlers. You can see this [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/1.21.0/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsHostBuilderExtensions.cs#L50).
- I don't see any authentication or authorization setup in your snippet. Are you doing so within `RegisterFunctions`?

I would advise starting a new app from scratch, make sure you configure auth and the functions authorization middleware, create a simple test function in your app and once you see it working, start moving the existing pieces one by one to try to find what is affecting middleware initialization.

**Comment by artmasa** [comment] 2024-04-25 16:28
I will go ahead and close this issue as I cannot reproduce this behavior from a ASP.NET Core integrated Isolated project

**Closed** 2024-04-25 16:28 UTC
Labels: question
