### ISSUE TITLE
Getting 401 while executing the function

### ISSUE THREAD

**Issue by devagarwal007** [dark-loop/functions-authorize#13] opened 2022-11-16 11:53 UTC
Error -> 
Exception while executing function: ABC 401 Authorization error encountered. This is the only way to stop function execution. The correct status has been communicated to the caller.

Method -> DarkLoop.Azure.Functions.Authorize.Security.FunctionsHttpAuthorizationHandler.BombFunctionInstance

//start up configuration
```
builder.Services.AddFunctionsAuthorization(options =>
        {
            options.DefaultPolicy = new AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser()
                .AddAuthenticationSchemes(Constants.Bearer)
                .Build();
        });
```

```
services
            .AddFunctionsAuthentication(options => options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
//Some code here
}
```

//Function file
```
[FunctionAuthorize(AuthenticationSchemes = Constants.Bearer)]
[FunctionName("ABC")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "ROUTE")] HttpRequest request,
        string data,
        ILogger logger
    )
    {
//Code
}
```

How to resolve this issue?, Please help.

**Comment by artmasa** [comment] 2022-11-18 21:51
@devagarwal007 this is the expected behavior for this extensions. Azure functions in hosted mode does not provide an easy way for middleware that can interface with ASP.NET core authNZ modules.  We need to throw an exception at `DarkLoop.Azure.Functions.Authorize.Security.FunctionsHttpAuthorizationHandler.BombFunctionInstance` to stop the function execution. If we don't stop it here your function logic still executes, and even when the user gets an unauthorized status there might be logic in your function that changes data in a backend system and we cannot let that happen.

**Comment by devagarwal007** [comment] 2022-11-19 03:33
But when I use [FunctionAuthorize] instead of FunctionAuthorize(AuthenticationSchemes = Constants.Bearer)] it is allowing me to execute the function, just wanted to know why it is not allowing when we add authenticationschemes validation in case of valid token.

**Comment by artmasa** [comment] 2022-11-19 14:15
@devagarwal007 I see, let me look into that.

**Comment by artmasa** [comment] 2022-11-22 14:45
@devagarwal007 I have tested your scenario, and everything works as expected.
Have you verified `JwtBearerDefaults.AuthenticationScheme` and `Constants.Bearer` are the same?
Based on how you are configuring `options.DefaultPolicy` I don't think there's a need to override it. I would just simply call `builder.Services.AddFunctionsAuthorization()` which it will generate same requirements for policy.

**Comment by artmasa** [comment] 2022-11-28 15:49
Based on my latest tests, it seems Azure Functions now just forwards the `Authorization` header to the functions host, along with the already decoded token components headers (`X-MS-CLIENT-PRINCIPAL-NAME`, `X-MS-CLIENT-PRINCIPAL-ID`, `X-MS-CLIENT-PRINCIPAL-IDP`, `X-MS-CLIENT-PRINCIPAL`).

**Comment by artmasa** [comment] 2022-12-09 22:39
@devagarwal007 I will go ahead and close this issue. Please let me know if you keep having this problem. Thanks

**Closed by artmasa** 2022-12-09 22:39 UTC
Labels: question

**Comment by ScotteYx** [comment] 2023-09-06 21:40
I think I am experiencing this issue.

Deployed to Azure via a Static Web App with a Managed v4 Functions API.

Locally works fine, but deployed I receive nothing but a 401.

**Comment by ScotteYx** [comment] 2023-09-07 10:49
For anyone stumbling across this, here's the code you need to get it working:

```
                    options.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
                        {
                            string accessToken = context.Request.Headers["access_token"];

                            // If no authorization header found, nothing to process further
                            if (string.IsNullOrEmpty(accessToken))
                            {
                                context.NoResult();
                                return Task.CompletedTask;
                            }

                            if (accessToken.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                            {
                                context.Token = accessToken.Substring("Bearer ".Length).Trim();
                            }

                            // If no token found, no further work possible
                            if (string.IsNullOrEmpty(context.Token))
                            {
                                context.NoResult();
                                return Task.CompletedTask;
                            }

                            return Task.CompletedTask;
                        }
                    };
```

You essentially need to use a different header for your Authorization until Azure fix their static web app issue. This uses the `access_token` header.

**Comment by rishabhdugar** [comment] 2023-12-28 05:17
I am still facing the issues, tried above remediations but still getting 401.
What i am trying is , protected azure function via portal Auethnetication, Configured Azure AD and token/audience correctly , Trying with postman by generating token aith client secret against the ad, and calling the function.

My startup looks like below, i need to use Darkloop so that i could get token azquisition working and allow function to be authorized, 
my function trigger is Ananonymous
```
builder
    .AddAuthentication()
    .AddJwtBearer(options =>
    {
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                string accessToken = context.Request.Headers["access_token"];

                // If no authorization header found, nothing to process further
                if (string.IsNullOrEmpty(accessToken))
                {
                    context.NoResult();
                    return Task.CompletedTask;
                }

                if (accessToken.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                {
                    context.Token = accessToken.Substring("Bearer ".Length).Trim();
                }

                // If no token found, no further work possible
                if (string.IsNullOrEmpty(context.Token))
                {
                    context.NoResult();
                    return Task.CompletedTask;
                }

                return Task.CompletedTask;
            }
        };
    })
    .AddOpenIdConnect(options =>
    {
        configuration.GetSection("AzureAd").Bind(options);
        options.SaveTokens = true;
    })
    .AddMicrosoftIdentityWebApi(
        configuration,
        configSectionName: "AzureAd",
        Scheme.TokenAcquisitionForUser.ToString()
    )
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddDistributedTokenCaches();
```

Any thoughts @artmasa  @devagarwal007  @ScotteYx

**Comment by rishabhdugar** [comment] 2023-12-28 05:29
When using Access Token Url as https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token i get 403 Forbidden and when using https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token i get 401 Unauthorized
Read somewhere that v2.0 is not supported so tried both

i do not have any inbound IP restriction on function networking
