### ISSUE TITLE
Azure broke auth

### ISSUE THREAD

**Issue by helgeu** [dark-loop/functions-authorize#48] opened 2024-05-03 19:41 UTC
We have been using Darkloop and FunctionAuthorize for a long time. A few days back this just stopped working totally when we are deploying new versions of our code (no changes to Darkloop or auth), and the azure functions are dead upon deployment. Fortunately we have these in slot so prod was not affected.

![image](https://github.com/dark-loop/functions-authorize/assets/29071829/150df868-8fc2-4bc6-b2fc-0b43b2f9aaf6)

The function app keys are also totally dead.

![image](https://github.com/dark-loop/functions-authorize/assets/29071829/4e8be3f1-3a28-4107-a2eb-eb4231b2c5ea)

Removing Darkloop nuget package its possible to get the Azure function running again, but of course the authorization is gone. 

Reporting this to Microsoft first since we was rather clear something had changed in Azure. Microsoft admits this but blames the way Darkloop is implemented.

![image](https://github.com/dark-loop/functions-authorize/assets/29071829/22b16f38-e5ef-4d09-a1a9-4ba13402a8b8)

We are using f# for Azure functions and have this code:

```fsharp
namespace AzureFunctions.Startup

open ServiceSetup
open AzureFunctionsDependencyInjectionExtensions.Config
open Microsoft.Azure.Functions.Extensions.DependencyInjection
open Microsoft.Extensions.DependencyInjection
open Microsoft.AspNetCore.Authentication.JwtBearer
open System
open Microsoft.AspNetCore.Authentication
open Microsoft.Extensions.Configuration

[<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
module DependencyInjectionStartup =
    let setupAuthenticationScheme (options: AuthenticationOptions) =
        options.DefaultAuthenticateScheme <- JwtBearerDefaults.AuthenticationScheme
        options.DefaultChallengeScheme <- JwtBearerDefaults.AuthenticationScheme

    let setupJwtAuthorization authority audience (options: JwtBearerOptions) =
        options.Authority <- authority
        options.Audience <- audience

    type HealthCheckSetupFunctionStartup() =
        inherit FunctionsStartup()

        override this.Configure(builder: IFunctionsHostBuilder) : unit =
            let services = builder.Services
            let sp = services.BuildServiceProvider()
            let conf = sp.GetService<IConfiguration>()

            let authIssuer = conf["Authorization:Issuer"]
            let authAudience = conf["Authorization:Audience"]

            let setupJwtAuth = setupJwtAuthorization authIssuer authAudience

            // For some reason, authentication setup needs to be called here
            // there is some problem with doing it withing AddDependencyInjection
            // reason unknown, needs further investigation
            builder.Services
                .AddFunctionsAuthentication(Action<AuthenticationOptions>(setupAuthenticationScheme))
                .AddJwtBearer(Action<JwtBearerOptions>(setupJwtAuth), true)
            |> ignore

            builder.Services.AddFunctionsAuthorization() |> ignore

            builder.AddDependencyInjection(fun s -> s |> setupServices conf) |> ignore

    [<assembly: FunctionsStartup(typeof<HealthCheckSetupFunctionStartup>)>]
    do ()
```

See also caveats from Microsoft related to auth*:

https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#caveats

![image](https://github.com/dark-loop/functions-authorize/assets/29071829/12a9adb2-99e1-4bf6-b612-48c4b6cc4e82)

I do suspect we might have some bad code after all, and any pointers for helping out would be highly appreciated.

Thanks in advance.

**Comment by josbol** [comment] 2024-05-03 22:39
I can confirm this. I just checked the status of two function apps, one running on runtime 3.x (deprecated) and the other on 4.x. both show the error status, but the apps still respond as expected. In the log stream errors show that the portal is unable to authenticate, hence the error.

Note: we did not upgrade to the 4.x nuget package of this project yet.

Last deploy

**Comment by Wotee** [comment] 2024-05-04 12:45
I can confirm this in in-process functions as well.
After some debugging, I found out that if I set 
’removeBuiltInConfig’ parameter in ’AddJwtBearer’ to ’false’, the function seems to work as it used to be. Haven’t done further validations yet, but wanted to share my findings asap if others are struggling with this too.

**Comment by josbol** [comment] 2024-05-04 14:38
> set ’removeBuiltInConfig’ parameter in ’AddJwtBearer’ to ’false’

I tested your suggestion on both an 3.x app and a 4.x app, but unfortunately it didn't work :(

4.x Function app
Darkloop 4.0.1
Functions SDK 4.3.0
Only uses one authentication scheme: Bearer

3.x Function app
Darkloop 3.1.3
Azure Functions SDK 3.1.2

Only uses one authentication scheme: Bearer

I have other apps that use multiple authentication schemes and/or Microsoft AAD which I haven't tested yet. Especially the AAD  auth scheme is very finicky when it comes to compatibility with certain other nuget packages, so I guess it's better to stick with testing the simpler setups first?

**Comment by josbol** [comment] 2024-05-06 13:40
Updating my previous results:

the 3.x function app now is no longer warning it can't list the functions and now it shows '3.22.0.0' for the Runtime Version, however it seems that ArmToken autentication is still broken:

2024-05-06T13:36:41Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 7 items
2024-05-06T13:36:41Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0036ms - processed: 0 items - remaining: 7 items
2024-05-06T13:36:48Z   [Verbose]   Request successfully matched the route with name 'negotiate' and template 'api/negotiate'
2024-05-06T13:36:48Z   [Information]   Executing 'negotiate' (Reason='This function was programmatically called via the host APIs.', Id=c881a61f-0fef-49c2-b973-d661cb6e1f17)
2024-05-06T13:36:48Z   [Verbose]   AuthenticationScheme: ArmToken was not authenticated.
2024-05-06T13:36:48Z   [Information]   Failed to validate the token.
2024-05-06T13:36:48Z   [Information]   Bearer was not authenticated. Failure message: IDX10231: Audience validation failed. Delegate returned false, securitytoken: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2024-05-06T13:36:48Z   [Information]   Authorization failed.

**Comment by josbol** [comment] 2024-05-06 16:39
Specifiying a scheme name  when using a AddJwtBearer() seems to be solving the problem:

` .AddJwtBearer("YourSchemeName",options =>
 {
....
});
`

Note that in case the removeBuiltInConfig parameter has to be removed.

This causes authentication of the functions to work and I don't see any errors in the azure portal.

**Comment by artmasa** [comment] 2024-05-07 01:06
I will take a look at this soon.

**Comment by helgeu** [comment] 2024-05-07 07:58
The named variant did the trick for us too. So it might just be a matter of updating the documentation part of the readme a bit @artmasa and include this "trick" as a fix for the change in Azure.

**Comment by Wotee** [comment] 2024-05-07 09:24
The variant with the scheme name seems to fix our problems as well

**Comment by artmasa** [comment] 2024-05-08 20:37
Yes, any custom scheme should work. The reason I created `AddJwtBearer` with `removeBuiltInConfig` was specifically to use the standard `Bearer` scheme. In the past this scheme was only added but not really used by the host.

It seems now, and I think because of the company wide security [push](https://www.microsoft.com/en-us/security/blog/2024/05/03/security-above-all-else-expanding-microsofts-secure-future-initiative/) (which I think it's great), the portal is enforcing using this scheme to communicate with the host to retrieve runtime and functions information. I wish they had used a custom scheme for this purpose and leave the general one for consumers. Although this is not officially supported.

It's also breaking to some extent the Isolated functions. At least you are able to see the functions in the portal, but runtime information shows **Error** like in the image above.

Thanks for reporting this. I will adjust the library documentation and mark the default scheme method obsolete with a link to documentation.

**Comment by josbol** [comment] 2024-05-09 13:03
Knowing "Bearer" can't be used without breaking stuff on azure, what about creating a overloading method that instead of clearing the previous config, simply registers it by default with "BearerCustom" and have the FunctionAuthorize attribute default to that scheme as well? This possibly breaks backward compatibility, but even so I think it's preferable over having to specify the custom scheme with every use of the authorizefunction attribute.

**Comment by artmasa** [comment] 2024-05-09 13:18
@josbol, my fear is that this can cause confusion, by just leaving it as `AddJwtBearer` with no parameter for name, communicates to the user "Bearer" scheme is being configured.
This is what I'm proposing
```csharp
[Obsolete("<deprecation-reason>. Use AddFunctionsJwtBearer instead")]
public static AuthenticationBuilder AddJwtBearer(
    this FunctionsAuthenticationBuilder builder, Action<JwtBearerOptions> configure, bool removeBuiltInConfig)
{
    ...
}

public static AuthenticationBuilder AddFunctionsJwtBearer(
    this FunctionsAuthenticationBuilder builder, Action<JwtBearerOptions> configure)
{
    return builder.AddJwtBearer("FunctionsBearer", configure);
}
```
WDYT?

**Comment by josbol** [comment] 2024-05-09 13:44
Sounds good to me!

**Comment by artmasa** [comment] 2024-05-21 14:45
Here is the PR #50 for the proposed changes. Can you guys help me review. I would like to get feedback on the readme docs?

**Comment by josbol** [comment] 2024-05-21 18:58
I reviewed the PR and left some comments, but after it was merged. It's just some comments for the docs though, nothing critical.

**Comment by artmasa** [comment] 2024-05-21 19:00
Thanks @josbol, taking a look

**Closed** 2024-05-22 20:10 UTC
Labels: help wanted
