### ISSUE TITLE
Exception when try to add policy by using 

### ISSUE THREAD

**Issue by yongding422** [dark-loop/functions-authorize#2] opened 2021-07-27 23:01 UTC
When trying to add the authorization policy, getting following exception:
![image](https://user-images.githubusercontent.com/5891685/127238175-ad7fe31a-cf19-42c0-934b-ed986ffb02f1.png)

I am using Azure Function V3, and here are packages my project referencing.
![image](https://user-images.githubusercontent.com/5891685/127238298-8ad4a522-7739-448b-934a-5c9b9d3a1f0b.png)

Could you please help to take a look? Is there any package I am missing? 

Thank you.

**Comment by artmasa** [comment] 2021-07-30 18:10
Thanks for reporting @yongding422. Let me look into this.

**Comment by artmasa** [comment] 2021-07-30 19:10
As a workaround at this moment. Can you add a reference to `Microsoft.AspNetCore.Authorization` >= 3.0.0 to your project?
I need to do some more testing to make sure the functionality on this assembly implements the prior versions had.

**Comment by artmasa** [comment] 2021-07-30 19:38
@yongding422, a new version of the package is available [3.0.12-preview-210730-1](https://www.nuget.org/packages/DarkLoop.Azure.Functions.Authorize/3.0.12-preview-210730-1)

For details on the problem take a look at this: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#authorization-addauthorization-overload-moved-to-different-assembly

A direct dependency to `Microsoft.AspNetCore.Authorization` `>=3.0.0` has been added to package

**Comment by yongding422** [comment] 2021-08-02 21:52
Thanks for your response. I tested the new version by creating a new function app, however this time I got following exception:
![image](https://user-images.githubusercontent.com/5891685/127927938-c407e043-7e52-42df-9b43-14ef697e7ec2.png)

**Comment by artmasa** [comment] 2021-08-04 13:59
@yongding422, the problem is that the package targets .NET Standard 2.1 because I didn't want to target a specific runtime. 3.0, 3.1 etc..., so I'm referencing `Microsoft.AspNetCore.Authentication.JwtBearer 2.2.0` 
If for example you are using netcoreapp3.1 in your project as the target framework and adding JWT auth for authentication, add the specific version of `Microsoft.AspNetCore.Authentication.JwtBearer` for your specific project (3.1.1 for example)
Based on my testing, once I add the more specific version of the package to my functions project, the runtime is able to target the right method for Authorization.

Please let me know if this solves the problem.

**Comment by yongding422** [comment] 2021-08-12 20:28
Hi Arturo,
Thank you for your response. It worked after I upgrade the package `Microsoft.AspNetCore.Authentication.JwtBearer`. However after I deployed the function app to Azure, from the Azure portal, it cannot recognize the function app runtime. I am able to call the function by using the function url, however from the Azure portal it shows that function runtime is unreachable, and I cannot find any endpoints when trying to import endpoints to APIM. Have you ran into the same issue?

Thanks

**Comment by yongding422** [comment] 2021-08-12 22:16
Hi Arturo,

I did some search online, and found out this is an knowing issue for Function App, there is a workaround for it, but looks like this workaround solution only works for .net core 3.1. Here is the url -- https://github.com/AzureAD/microsoft-identity-web/issues/916

Thanks,

**Comment by artmasa** [comment] 2021-11-18 20:01
@yongding422, thanks for the update. I will close this issue

**Closed by artmasa** 2021-11-18 20:01 UTC
